### ISSUE TITLE
Ultimaker 2 Extended + code

### ISSUE THREAD

**Issue by WissamKdotcom** [Ultimaker/Ultimaker2ExtendedPlus#1]
Hello,

I have a tiny edit I want to do to the code of my printer's firmware, UM2E+, but when I use Ultimaker2Marlin code, my steppers start vibrating like crazy, in a way that suggests that they have insufficient torque. So basically that code is unusable. I looked into it some more and found out that I should edit twi.c file in Arduino before compiling, and I did but that didn't change anything. So I'm guessing that code doesn't work for my UM2E+. I expected that I should find the code here but it doesn't exist here either. Help?

PS. I barely know about programming so excuse my possible terminology mistakes.

**Comment by Ghostkeeper** [comment]
Yeah it's a bit confusing with inconsistent repository names, branch names and repository layouts.

The UM2+ has a different repository than the UM2. You should be using the `UM2.1-Firmware` repository. Specifically, the `UM2.1_JarJarExtended` branch there: https://github.com/Ultimaker/UM2.1-Firmware/tree/UM2.1_JarJarExtended

I hope that works better for you. I've personally compiled that branch and put that in Cura for its firmware update feature, so it had better work! Let me know if you need more help.
